name: Shell Style Checks

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    shellcheck:
        runs-on: ubuntu-latest
        # Ubuntu's ShellCheck is old enough to not have --severity
        container: fedora:latest
        steps:
            - uses: actions/checkout@v2
            - run: dnf install -y ShellCheck
            - run: shellcheck --severity=warning **/*.sh
