name: CI on Ubuntu

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        # This job runs directly on the Ubuntu host provided by GitHub Actions
        runs-on: ubuntu-latest

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # This means clone the git repo
            - uses: actions/checkout@v2

            # Within the container, install the build dependencies and
            # test suite dependencies
            - name: Install Build Dependencies
              run: sudo make instreqs

            # Set up the source tree to build
            - name: setup
              run: meson setup build --werror -Db_buildtype=debug -Db_coverage=true

            # Compile the software
            - name: build
              run: ninja -C build -v

            # Run the test suite
            - name: test
              run: meson test -C build -v

            # Generate code coverage reports (requires
            # -Db_coverage=true on 'meson setup')
            - name: coverage
              run: ninja -C build coverage
