name: rpminspect CI on Ubuntu

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Build Dependencies
              run: sudo apt-get install meson
            - name: setup
              run: meson setup build
            - name: build
              run: ninja -C build
            - name: check
              run: meson check -C build
