name: rpminspect CI on Ubuntu

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Build Dependencies
              run: sudo apt-get install meson gettext libjson-c-dev libxmlrpc-core-c3-dev librpm-dev libarchive-dev libelf-dev libkmod-dev libcurl4-openssl-dev zlib1g-dev libyaml-dev libssl-dev libcap-dev
            - name: setup
              run: meson setup build
            - name: build
              run: ninja -C build
            - name: check
              run: meson check -C build
